"""
Tests to verify that Field objects are rendered correctly.

"""
from crispy_forms_gds.layout import Field


def test_wrapper_class_is_added_to_context():
    """Verify that if wrapper_class is listed in the kwargs it is added to the
    context so it will be available in the template."""
    field = Field("name", wrapper_class="wrapper")
    assert field.context["wrapper_class"] == "wrapper"


def test_fullname_field_attributes():
    """Verify the correct attributes are generated by Field.fullname()."""
    field = Field.fullname("field")
    assert field.attrs["autocomplete"] == "name"
    assert field.attrs["spellcheck"] == "false"


def test_email_field_attributes():
    """Verify the correct attributes are generated by Field.email()."""
    field = Field.email("field")
    assert field.attrs["autocomplete"] == "email"
    assert field.attrs["spellcheck"] == "false"


def test_number_field_attributes():
    """Verify the correct attributes are generated by Field.fullname()."""
    field = Field.number("field")
    assert field.attrs["inputmode"] == "numeric"
    assert field.attrs["pattern"] == "[0-9]*"
